### ISSUE TITLE
compiler errors

### ISSUE THREAD

**Issue by ElectroLund** [AutoHotkey-V2/log4ahk#19]
I'm assuming that because this is for AHK 2.x, it won't compile for v1.33?

I'm seeing errors with some functions.  One example:

(266) : ==> Call to nonexistent function.  Specifically: FormatTime(, "yyyy/MM/dd hh:mm:ss")

**Comment by hoppfrosch** [comment]
Correct - its intended for use with Autohotkey V2.

As the Readme states, this library was developed with AHK V2.0.a100 - and would not work with more recent versions of AHK v2 due to many breaking changes. It needs to be updated ... ;-(
